### ISSUE TITLE
Dynamo is not compatible with application properties in YAML format

### ISSUE THREAD

**Issue by tommy-ocs** [opencirclesolutions/dynamo#219]
When using `application.yml`, properties will not resolve in Dynamo.

An example:
In a properties file, we can define:
```properties
Open Circle Solutions.entity.model.package.names=com.example.package
```

If we translate this to YAML, the property will not be read:
```yaml
ocs:
  entity:
    model:
      package:
        names: com.example.package
```
